apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-default-ns
  namespace: default
spec:
  limits:
  - max:
      cpu: "512m"
      memory: "512Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Container

