
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: dev
  labels:
    app: myapp
spec:
  containers:
    - name: container1
      image: mongo
      ports:
        - containerPort: 123
          targetPort: 8080 
      volumeMounts:
        - name: vol-1
          mountPath: /tmp/mongodb        
  volumes:
    - name: vol-1
      hostPath:
        path: /tmp/mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 123
      targetPort: 8080

